DEVELOPMENT_202_06_01_1205. <COMPILE_ERROR>.
undefined reference to `CLIBOpenEpiCentre::Data_Control::app_FUNCT_flip_Input_DoubleBuffer()'

implemented:
- WriteQue CMakeLists.txt.
- LaunchQue CMakeLists.txt.
- OpenEpiCentre CMakeLists.txt.
- TestBench CMkaeLists.txt.
   - fixed CLIB name.
- fixed CMake import #include for libraries.
- HACKED? missing data_control.cpp
   - added cpp file.

todo:
- build TestBench.
- run SIMULATION.