DEVELOPMENT_202_06_04_18229. <LINKING_ERROR>.
$ cmake -B build
-- The CXX compiler identification is GNU 13.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.4s)
-- Generating done (0.0s)
-- Build files have been written to: /home/brenton-james/CLionProjects/OpenEpiCentre_BackEndUbuntu/OpenEpiCentre_BackEndUbuntu/TestBench/build

$ cmake --build build
[  1%] Building CXX object libs/CLIB_WriteQueForThreadsAt_SIMULATION/CMakeFiles/CLIB_WriteQueForThreadsAt_SIMULATION.dir/src/CLIB_WriteEnableForThreadsAt_SIMULATION.cpp.o
[  3%] Building CXX object libs/CLIB_WriteQueForThreadsAt_SIMULATION/CMakeFiles/CLIB_WriteQueForThreadsAt_SIMULATION.dir/src/WriteEnableForThreadsAt_SIMULATION_Framework.cpp.o
[  5%] Building CXX object libs/CLIB_WriteQueForThreadsAt_SIMULATION/CMakeFiles/CLIB_WriteQueForThreadsAt_SIMULATION.dir/src/WriteEnableForThreadsAt_SIMULATION_Global.cpp.o
[  7%] Building CXX object libs/CLIB_WriteQueForThreadsAt_SIMULATION/CMakeFiles/CLIB_WriteQueForThreadsAt_SIMULATION.dir/src/WriteEnableForThreadsAt_SIMULATION.cpp.o
[  9%] Building CXX object libs/CLIB_WriteQueForThreadsAt_SIMULATION/CMakeFiles/CLIB_WriteQueForThreadsAt_SIMULATION.dir/src/WriteEnableForThreadsAt_SIMULATION_Control.cpp.o
[ 11%] Linking CXX static library libCLIB_WriteQueForThreadsAt_SIMULATION.a
[ 11%] Built target CLIB_WriteQueForThreadsAt_SIMULATION
[ 13%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/CLIB_OpenEpiCentre.cpp.o
[ 15%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/engine/Framework_Server.cpp.o
[ 16%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/engine/Global.cpp.o
[ 18%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/structs/Input.cpp.o
[ 20%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/structs/Output.cpp.o
[ 22%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/structs/Concurrent.cpp.o
[ 24%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/structs/User_Input.cpp.o
[ 26%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/structs/User_Output.cpp.o
[ 28%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/structs/User_Algorithm.cpp.o
[ 30%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/structs/praise_sets/Algorithm_praise0.cpp.o
[ 32%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/structs/praise_sets/Input_praise0.cpp.o
[ 33%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/structs/praise_sets/Output_praise0.cpp.o
[ 35%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/engine/Server.cpp.o
[ 37%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/engine/Algorithms.cpp.o
[ 39%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/engine/Data.cpp.o
[ 41%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/engine/Data_Control.cpp.o
[ 43%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/engine/Execute.cpp.o
[ 45%] Building CXX object libs/CLIB_OpenEpiCentre/CMakeFiles/CLIB_OpenEpiCentre.dir/src/engine/Execute_Control.cpp.o
[ 47%] Linking CXX static library libCLIB_OpenEpiCentre.a
[ 47%] Built target CLIB_OpenEpiCentre
[ 49%] Building CXX object CMakeFiles/TestBench.dir/Main.cpp.o
[ 50%] Building CXX object CMakeFiles/TestBench.dir/IO.cpp.o
[ 52%] Building CXX object CMakeFiles/TestBench.dir/src/engine/Algorithms.cpp.o
[ 54%] Building CXX object CMakeFiles/TestBench.dir/src/engine/App.cpp.o
[ 56%] Building CXX object CMakeFiles/TestBench.dir/src/engine/Data.cpp.o
[ 58%] Building CXX object CMakeFiles/TestBench.dir/src/engine/Execute.cpp.o
[ 60%] Building CXX object CMakeFiles/TestBench.dir/src/engine/Execute_Control.cpp.o
[ 62%] Building CXX object CMakeFiles/TestBench.dir/src/engine/Framework_App.cpp.o
[ 64%] Building CXX object CMakeFiles/TestBench.dir/src/engine/Global.cpp.o
[ 66%] Linking CXX executable TestBench

undefined reference to `CLIBOpenEpiCentre::Framework_Server::dyn_CLASS_get_ptr_Global()'

implemented:
- WriteQue CMakeLists.txt.
- LaunchQue CMakeLists.txt.
- OpenEpiCentre CMakeLists.txt.
- TestBench CMkaeLists.txt.
   - fixed CLIB name.
- fixed CMake import #include for libraries.
- added missing data_control.cpp in openepicentre.
   - added member functions.

todo:
- build TestBench.
- run SIMULATION.