DEVELOPMENT_202_06_01_1205. <COMPILE_ERROR>.
[ 66%] Linking CXX executable TestBench
undefined reference to `CLIBOpenEpiCentre::Framework_Server::dyn_CLASS_get_ptr_Global()'

implemented:
- WriteQue CMakeLists.txt.
- LaunchQue CMakeLists.txt.
- OpenEpiCentre CMakeLists.txt.
- TestBench CMkaeLists.txt.
   - fixed CLIB name.
- fixed CMake import #include for libraries.
- added missing data_control.cpp in openepicentre.
   - added member functions.

todo:
- build TestBench.
- run SIMULATION.